name: Send a slack notification when a contributor comments on issue

on:
  issue_comment:
    types: [created]

jobs:
  contributor_issue_comment:
    uses: testiamshobh/.github/.github/workflows/notify_team_new_comment.yml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_COMMUNITY_NOTIFICATIONS_WEBHOOK_URL: ${{ secrets.SLACK_COMMUNITY_NOTIFICATIONS_WEBHOOK_URL }}